package com.inboxintelligence.persistence.model.enums;

public enum ProcessedStatus {

    EMAIL_RECEIVED,
    CONTENT_SAVED,
    ATTACHMENT_SAVED,
    INGESTION_FAILED,

    PUBLISHED_FOR_SANITIZATION,
    SANITIZATION_STARTED,
    SANITIZATION_COMPLETED,
    SANITIZATION_FAILED,

    PUBLISHED_FOR_NORMALIZATION,
    NORMALIZATION_STARTED,
    NORMALIZATION_COMPLETED,
    NORMALIZATION_FAILED,

    PUBLISHED_FOR_EMBEDDING,
    EMBEDDING_STARTED,
    EMBEDDING_GENERATED,
    EMBEDDING_FAILED,

    PUBLISHED_FOR_CLUSTER_ASSIGNMENT,
    CLUSTER_ASSIGNMENT_STARTED,
    CLUSTER_ASSIGNMENT_COMPLETED,
    CLUSTER_ASSIGNMENT_FAILED,

    UNKNOWN_FAILURE

}
